### ISSUE TITLE
Weird file showing in my report

### ISSUE THREAD

**Issue by IonelLupu** [cenfun/nextjs-with-playwright#1]
I got this weird file in my report in my project and I really can't see where it comes from and how I can remove it. I tried deleting each file from the project and I got to a point where `next/link` makes it show up. But I can't make it replicate in your repo.

Before pushing my repo with the replication, do you know how to fix this issue?

![image](https://github.com/user-attachments/assets/71a12df5-903e-4158-b77d-a459aa50209a)

**Comment by cenfun** [comment]
It should come from `dist` file, please try option `sourceFilter` to remove it.

**Comment by IonelLupu** [comment]
@cenfun , I tried that. My `sourceFilter` doesn't include this file or folder at all. Here is my `monocart-reporter` config:
```
const coverageReportOptions: CoverageReportOptions = {
    // logging: 'debug',
    name: 'Next.js V8 Coverage Report',
    lcov: true,

    entryFilter: entry => {
        return entry.url.includes('next/static/chunks') || entry.url.includes('next/server/app')
    },

    sourceFilter: sourcePath => {
        return sourcePath.startsWith('app') || sourcePath.startsWith('actions') || sourcePath.startsWith('designSystem')
    },

    onEnd: async coverageResults => {
        // Not sure if we need to check for line coverage thresholds here. We already  use the zgosalvez/github-actions-report-lcov inside github actions to check for minimum thresholds

        console.log('check thresholds ...', thresholds)
        const errors: string[] = []
        const { summary } = coverageResults as CoverageResults
        Object.keys(thresholds).forEach(k => {
            const pct = summary[k as keyof typeof summary]?.pct
            const threshold = thresholds[k]
            if (pct && threshold && pct < threshold) {
                errors.push(`Coverage threshold for ${k} (${pct} %) not met: ${threshold} %`)
            }
        })
        if (errors.length) {
            const errMsg = errors.join('\n')
            console.error(EC.red(errMsg))
            // process.exit(1)
        }
    },

    sourcePath: fileSource => {
        const list = [
            '_N_E/',
            'hotel/', // from package.json -> "name" property
        ]
        for (const pre of list) {
            if (fileSource.startsWith(pre)) {
                return fileSource.slice(pre.length)
            }
        }
        return fileSource
    },

    reports: ['v8', 'console-details'],
}
```

As you can see, the `_next/static/chunks` is not mentioned there (except `entryFilter`, but I don't think it's related)

**Comment by cenfun** [comment]
Sorry, I didn't notice it started with 'localhost-3000', it should use `entryFilter` to remove it.

**Comment by IonelLupu** [comment]
@cenfun, how would you filter it out without hardcoding the exact file name? The file is generated automatically and it always has a random name after each build:
```tsx
entryFilter: entry => {
        console.log('entry url ->', entry.url)
        if (entry.url.includes('eefd5ad7673e3b21.js')) { // <-- hardcoded value not OK
            return false
        }
        return entry.url.includes('next/static/chunks') || entry.url.includes('next/server/app')
    },

```

If I exclude the entire `next/static/chunks` directory, I don't get coverage anymore.

Here is how the file URL when I print all of the entries:
![image](https://github.com/user-attachments/assets/670c2309-e52d-4a4e-b42b-4a2182fab593)


I get a lot of them in the same directory. Any other hints? 😄

**Comment by cenfun** [comment]
Yes, it is a problem.
For `Monocart`, I don't think there is a good solution to filter those entries with the random file names.
But for `Next.js`, there might be an option to set these filenames to be human-readable. 
I'm not very familiar with Next.js, could you look for help from Next.js community?

for example: minify = false? something like that.

**Comment by IonelLupu** [comment]
@cenfun, you are a rock star. 🚀 

I initially tried the `swcMinify: false` option in Next.js, but it didn't work. It actually made things worse by showing 3 files with random names in the coverage instead of just one as previous.

It turns out I had to disable the minification from within Nextjs's webpack configs instead:
```js
const nextConfig = {
    /// ... some more configs
    webpack: config => {
        if (process.env.NODE_V8_COVERAGE) {
            Object.defineProperty(config, 'devtool', {
                get() {
                    return 'source-map'
                },
                set() {},
            })
        }
        
       if (process.env.NODE_ENV === 'test') { // <-- I added this
            return {
                ...config,
                optimization: {
                    minimize: false
                }
            };
        }
        return config
    },
}
```


I had to add an env variable when I build the project so that it builds it unoptimized ONLY for testing. Which means  I build the project for testing using this script in package.json: `"test:build": "NODE_ENV=test next build"`
