### ISSUE TITLE
Not compatible with Next.js 15

### ISSUE THREAD

**Issue by ogous** [cenfun/nextjs-with-playwright#3]
On Next.js v15 webpack `devtool` override is restricted. When this setup try to set it to `source-map` it was reverting to the `eval-source-map` in version 14 of Next.js. But in v.15 it reverts to `false`. So this behavior distracts a proper coverage reports for the project.

We need a workaround for version 15. Next.js team also seems like to encourage the use of `turbopack` instead of `webpack` in the future.

I am going to check if there are any workaround for `webpack` or migrating this setup to`turbopack` and will share the findings.

**Comment by cenfun** [comment]
Yes, we have some discussions and outputs here
https://github.com/cenfun/monocart-reporter/issues/161
Basically, there are some issues with nextjs15, which cannot filter source files well.
We still need to wait for nextjs15 to be more stable and have the same reasonable file structure as nextjs14.

**Comment by ogous** [comment]
@cenfun thanks! I will follow from the issue you shared, closing this one.

**Comment by stevez** [comment]
I found the same issue in nextjs 15
